name: cred_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.18.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  syncfusion_flutter_gauges: ^28.2.3
  loading_animation_widget: ^1.3.0
  # syncfusion_flutter_gauges: ^28.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true